app:
  file:
    root: /data/files
db:
  host: @db.host@
  port: @db.port@
  name: @db.name@
  username: @db.username@
  password: @db.password@
  ddl-auto: @db.ddl-auto@
server:
  contextPath: /
  port: ${port:9013}
  server-header: @project.artifactId@-@project.version@
spring:
  profiles:
    active: @spring-active-profiles@