spring:
  datasource:
    url: jdbc:postgresql://${db.host:localhost}:${db.port:5432}/${db.name:file}
    #driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect