#### Production Environment ####
spring:
  main:
    banner-mode: 'off'
logging:
  file: @project.artifactId@-@project.version@.log
  level: # one of TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
    root: ERROR
    tech.simter.file: WARN