server:
  contextPath: /
  port: ${port:9013}
  server-header: @project.artifactId@-@project.version@
spring:
  profiles:
    active: @spring-active-profiles@
  datasource:
    username: ${db.username:file}
    password: ${db.password:password}
    continue-on-error: false
    sql-script-encoding: UTF-8
app:
  file:
    root: /data/files